# wrangler.toml (wrangler v3.88.0^)
name = "skyoffice"
main = "server/worker-dist/server/worker/index.js"
compatibility_date = "2023-10-30"
compatibility_flags = ["nodejs_compat"]

[observability.logs]
enabled = true

# Durable Objects
[[durable_objects.bindings]]
name = "ROOMS"
class_name = "RoomDurableObject"

# Migrations for Durable Objects (free plan)
[[migrations]]
tag = "v1"
new_sqlite_classes = ["RoomDurableObject"]

# Variáveis de ambiente
[vars]
NODE_ENV = "production"

# Configurações de desenvolvimento
[env.dev]
name = "skyoffice-dev"

[env.dev.vars]
NODE_ENV = "development"
